#FROM java:8-jre
FROM java:8-jdk-alpine
MAINTAINER slimane G. <slimane@example.com.com>

ADD PrometheusDemo1-1.0-SNAPSHOT.jar /app/
CMD ["java", "-Xmx200m", "-jar", "/app/PrometheusDemo1-1.0-SNAPSHOT.jar"]

EXPOSE 9001